adopted: true
description: Read-only adapter to enrich an alert from Trend Micro Vision One (Workbench)
  and normalize into Alert.Enrichment.*.
dirtyInputs: true
id: SOC Trend Micro Alert Enrichment
inputs: []
name: SOC Trend Micro Alert Enrichment
outputs:
- contextPath: Alert.Enrichment.Provider
  description: Provider summary (name, workbenchUrl, alertId).
  type: unknown
- contextPath: Trend.V1.AlertDetailsRaw
  description: Raw JSON returned by trendmicro-visionone-get-alert-details.
  type: unknown
- contextPath: Alert.Enrichment.Entities
  description: Entities extracted from Trend alert details.
  type: unknown
- contextPath: Alert.Enrichment.Indicators
  description: Indicators extracted from Trend alert details.
  type: unknown
- contextPath: Alert.Enrichment.Mitre.Techniques
  description: MITRE techniques (IDs) from Trend alert details.
  type: unknown
- contextPath: Alert.Enrichment.Source.Trend
  description: Adapter bookkeeping flags.
  type: unknown
starttaskid: "0"
tags:
- SOC
- SOC_Framework
- Enrichment
- Trend Micro Vision One
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 09ff7a99-ab25-4eea-8022-12c55d265799
      iscommand: false
      name: ""
      playbooktaskmissingcomponent:
      version: -1
    taskid: 09ff7a99-ab25-4eea-8022-12c55d265799
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 192.5,
          "y": 50
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "101"
      "no":
      - "3"
      "yes":
      - "99"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: id
          filters:
          - - left:
                iscontext: true
                value:
                  simple: VisionOne.Alert_Details.alert
              operator: isNotEmpty
          root: VisionOne.Alert_Details.alert
    separatecontext: false
    skipunavailable: true
    task:
      brand: Builtin
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: f640a9af-d4ee-4c55-8af0-da08975e882d
      iscommand: false
      name: Does VisionOne Key exist?
      playbooktaskmissingcomponent:
      script: Exists
      type: condition
      version: -1
    taskid: f640a9af-d4ee-4c55-8af0-da08975e882d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 70,
          "y": 570
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "101"
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Alert.Provider.alertId
      value:
        complex:
          accessor: externallink
          root: issue
          transformers:
          - args:
              from:
                value:
                  simple: /workbench/alerts/
            operator: substringFrom
          - args:
              to:
                value:
                  simple: '?'
            operator: substringTo
    separatecontext: false
    skipunavailable: true
    task:
      brand: Builtin
      description: Set a value in context under the key you entered.
      id: b570cf07-5371-4cff-9f59-432456f61ddd
      iscommand: false
      name: Set provider alertId
      playbooktaskmissingcomponent:
      script: Set
      type: regular
      version: -1
    taskid: b570cf07-5371-4cff-9f59-432456f61ddd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 750
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: errorPath
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "101"
      "yes":
      - "100"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Trend Micro Vision One V3
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Check for an enabled Trend Micro Vision One instance.
      id: 22dbc7e1-ab76-41be-b04c-eacfc66e0ed4
      iscommand: false
      name: Trend Micro Vision One available?
      playbooktaskmissingcomponent:
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 22dbc7e1-ab76-41be-b04c-eacfc66e0ed4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 192.5,
          "y": 220
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Alert.Provider.alertId
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "99"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b5af4b24-f4cf-4fac-8398-8394ebbb51c9
      iscommand: false
      name: Do we have a Trend alert/workbench ID?
      playbooktaskmissingcomponent:
      type: condition
      version: -1
    taskid: b5af4b24-f4cf-4fac-8398-8394ebbb51c9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 295,
          "y": 930
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: errorPath
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "101"
      '#none#':
      - "99"
    note: false
    quietmode: 0
    scriptarguments:
      workbench_id:
        simple: ${Alert.Provider.alertId}
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Fetches details for a specific alert.
      id: 5660d7dd-e076-47e1-baf6-70e5a41c64b6
      iscommand: true
      name: Get Trend alert details (read-only)
      playbooktaskmissingcomponent:
      script: '|||trendmicro-visionone-get-alert-details'
      type: regular
      version: -1
    taskid: 5660d7dd-e076-47e1-baf6-70e5a41c64b6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 80,
          "y": 1110
        }
      }
  "99":
    continueonerrortype: ""
    id: "99"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 91e48ade-1332-41f3-9283-a16723530564
      iscommand: false
      name: Done
      playbooktaskmissingcomponent:
      type: title
      version: -1
    taskid: 91e48ade-1332-41f3-9283-a16723530564
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1295
        }
      }
  "100":
    continueonerrortype: ""
    id: "100"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c1542e43-2164-4107-8f6d-5c97e7be06b1
      iscommand: false
      name: Already Enriched
      playbooktaskmissingcomponent:
      type: title
      version: -1
    taskid: c1542e43-2164-4107-8f6d-5c97e7be06b1
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 70,
          "y": 400
        }
      }
  "101":
    continueonerrortype: ""
    id: "101"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: ca6bec1c-2fbf-4cb1-8a66-285d7caed20f
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      playbooktaskmissingcomponent:
      type: playbook
      version: -1
    taskid: ca6bec1c-2fbf-4cb1-8a66-285d7caed20f
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1290
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "5_100_yes": 0.79,
      "6_99_#default#": 0.82
    },
    "paper": {
      "dimensions": {
        "height": 1310,
        "width": 830,
        "x": 50,
        "y": 50
      }
    }
  }
fromversion: 5.0.0
